### PR TITLE
Fix property descriptions in the quick reference

### PR DESCRIPTION
**Pull request by zcorpan**

### CODE REVIEW

**Comment by jeremyroman** [comment]
Looks reasonable to me (well, we could bikeshed scheme/protocol, path/pathname and hash/fragment, but it probably doesn't matter in this context). Unfortunately I seem to not have been granted permission to review PRs since this was moved into whatwg.

@domenic do you know what's required for that?

**Review by sisidovski — APPROVED** [review]
LGTM unless we have bikeshedding.

**Comment by domenic** [comment]
https://github.com/whatwg/urlpattern/issues/195 might be relevant here.

Yes, both of you have the same permissions; Jeremy please try again?

**Review by jeremyroman — APPROVED** [review]

**Comment by jeremyroman** [comment]
I was able to approve, but I'm still not authorized to merge PRs due to branch protection.

**Comment by domenic** [comment]
I found a setting that seemed different between this and other standards. Give it a shot now?

**Pull request merged**
